### ISSUE TITLE
need add

### ISSUE THREAD

**Issue by ddkwork** [richardwilkes/mupdf#1]
Uname -m case aarch64* for arch  linux

**Comment by richardwilkes** [comment]
If you're asking for support to be added for ARM targets on linux, I'm afraid that's not practical for me, as I have no such targets.

**Comment by ddkwork** [comment]
> If you're asking for support to be added for ARM targets on linux, I'm afraid that's not practical for me, as I have no such targets.

Can i upload builded lib for make a pr？

**Comment by richardwilkes** [comment]
Since I could neither test it nor update it as I make other changes in the future, no. You’d be better off creating a fork of this repo and making whatever changes you deem appropriate instead.
